version: "3.10"

services:    
  web:
    container_name: billie
    build: .
    command: >
      bash -c """
              python manage.py runserver 0.0.0.0:8000
              """
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - billie_services
    
networks:
  billie_services: