# Generated by Django 5.0.6 on 2024-05-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetails',
            name='chat_response',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='classdetails',
            name='query_text',
            field=models.CharField(),
        ),
    ]
