# Generated by Django 5.0.6 on 2024-06-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_classdetails_chat_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetails',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
